"""
File System Watcher - Monitors a drop folder for new files.

When files are added to the Inbox folder, this watcher:
1. Detects the new file
2. Copies it to Needs_Action folder
3. Creates a metadata .md file with file information
4. Notifies the AI Employee to process

Usage:
    python filesystem_watcher.py /path/to/vault
"""

import shutil
import hashlib
from pathlib import Path
from datetime import datetime
from base_watcher import BaseWatcher


class FileSystemWatcher(BaseWatcher):
    """
    Watches the Inbox folder for new files and creates action files.
    """
    
    def __init__(self, vault_path: str, check_interval: int = 30):
        """
        Initialize the file system watcher.
        
        Args:
            vault_path: Path to the Obsidian vault root
            check_interval: Seconds between checks (default: 30)
        """
        super().__init__(vault_path, check_interval)
        self.drop_folder = self.vault_path / 'Inbox'
        self.processed_files = set()
        
        # Load already processed files from disk
        self._load_processed_files()
    
    def _load_processed_files(self):
        """Load hashes of already processed files to avoid duplicates on restart."""
        done_folder = self.vault_path / 'Done'
        if done_folder.exists():
            for f in done_folder.glob('FILE_*'):
                self.processed_files.add(f.name)
    
    def _get_file_hash(self, filepath: Path) -> str:
        """Calculate MD5 hash of a file for duplicate detection."""
        hash_md5 = hashlib.md5()
        with open(filepath, 'rb') as f:
            for chunk in iter(lambda: f.read(4096), b''):
                hash_md5.update(chunk)
        return hash_md5.hexdigest()
    
    def check_for_updates(self) -> list:
        """
        Check the Inbox folder for new files.
        
        Returns:
            List of new file paths to process
        """
        new_files = []
        
        if not self.drop_folder.exists():
            self.drop_folder.mkdir(parents=True, exist_ok=True)
            return []
        
        # Check all files in inbox
        for filepath in self.drop_folder.iterdir():
            if filepath.is_file() and not filepath.name.endswith('.md'):
                # Create unique identifier from filename + hash
                file_hash = self._get_file_hash(filepath)
                unique_id = f"{filepath.stem}_{file_hash[:8]}"
                
                if unique_id not in self.processed_files:
                    new_files.append(filepath)
                    self.processed_files.add(unique_id)
        
        return new_files
    
    def create_action_file(self, filepath: Path) -> Path:
        """
        Create an action file for a dropped file.
        
        Args:
            filepath: Path to the new file
            
        Returns:
            Path to the created action file
        """
        # Get file metadata
        stat = filepath.stat()
        file_size = stat.st_size
        created_time = datetime.fromtimestamp(stat.st_ctime).isoformat()
        modified_time = datetime.fromtimestamp(stat.st_mtime).isoformat()
        
        # Create unique ID
        file_hash = self._get_file_hash(filepath)
        unique_id = f"{filepath.stem}_{file_hash[:8]}"
        
        # Copy file to Needs_Action
        dest = self.needs_action / filepath.name
        shutil.copy2(filepath, dest)
        
        # Create metadata markdown file
        action_filename = self.generate_filename('FILE', unique_id)
        action_path = self.needs_action / action_filename
        
        # Determine priority based on keywords in filename
        filename_lower = filepath.name.lower()
        priority = 'high' if any(kw in filename_lower for kw in ['urgent', 'asap', 'invoice', 'payment']) else 'medium'
        
        content = f'''{self.create_frontmatter(
            item_type='file_drop',
            priority=priority,
            original_name=f'"{filepath.name}"',
            size=file_size,
            file_created=created_time
        )}

## File Information

- **Original Name:** {filepath.name}
- **Size:** {self._format_size(file_size)}
- **Created:** {created_time}
- **Modified:** {modified_time}
- **Location:** `Needs_Action/{filepath.name}`

## Content Preview

```
*File copied to Needs_Action folder for processing*
```

## Suggested Actions

- [ ] Review file content
- [ ] Categorize and tag
- [ ] Take required action
- [ ] Move to Done when complete

## Notes

*Add your notes here...*

---
*Generated by File System Watcher v0.1*
'''
        
        action_path.write_text(content, encoding='utf-8')
        return action_path
    
    def _format_size(self, size_bytes: int) -> str:
        """Format file size in human-readable format."""
        for unit in ['B', 'KB', 'MB', 'GB']:
            if size_bytes < 1024.0:
                return f"{size_bytes:.2f} {unit}"
            size_bytes /= 1024.0
        return f"{size_bytes:.2f} TB"


def main():
    """Main entry point for running the watcher."""
    import sys
    
    # Get vault path from command line or use default
    if len(sys.argv) > 1:
        vault_path = sys.argv[1]
    else:
        # Default to AI_Employee_Vault in current directory
        vault_path = Path(__file__).parent.parent / 'AI_Employee_Vault'
    
    vault_path = Path(vault_path).resolve()
    
    if not vault_path.exists():
        print(f"Error: Vault path does not exist: {vault_path}")
        print("Usage: python filesystem_watcher.py /path/to/vault")
        sys.exit(1)
    
    print(f"=== AI Employee File System Watcher ===")
    print(f"Vault: {vault_path}")
    print(f"Monitoring: {vault_path / 'Inbox'}")
    print(f"Output: {vault_path / 'Needs_Action'}")
    print(f"Press Ctrl+C to stop\n")
    
    watcher = FileSystemWatcher(str(vault_path), check_interval=30)
    watcher.run()


if __name__ == '__main__':
    main()
