"""
HITL Approval Workflow - Human-in-the-Loop approval management.

Manages approval requests for sensitive actions:
- Creates approval files in Pending_Approval/
- Monitors Approved/ folder for execution
- Tracks rejections and expiry
- Ensures AI never acts autonomously on sensitive matters

Usage:
    python hitl_approval.py /path/to/vault --create-approval --type payment --amount 500
    python hitl_approval.py /path/to/vault --check-approved
    python hitl_approval.py /path/to/vault --watch
"""

import os
import sys
import argparse
import json
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, Optional, List


class HITLApproval:
    """
    Human-in-the-Loop approval workflow manager.
    """

    def __init__(self, vault_path: str):
        """
        Initialize the approval workflow.

        Args:
            vault_path: Path to the Obsidian vault root
        """
        self.vault_path = Path(vault_path)
        
        # Folders
        self.pending_approval = self.vault_path / 'Pending_Approval'
        self.approved = self.vault_path / 'Approved'
        self.rejected = self.vault_path / 'Rejected'
        self.done = self.vault_path / 'Done'
        self.logs = self.vault_path / 'Logs'
        
        # Ensure folders exist
        for folder in [self.pending_approval, self.approved, self.rejected, self.done, self.logs]:
            folder.mkdir(parents=True, exist_ok=True)

    def create_approval(self, action_type: str, details: Dict, 
                        description: str = "", 
                        priority: str = 'medium',
                        expires_in_hours: Optional[int] = None) -> Path:
        """
        Create an approval request.

        Args:
            action_type: Type of action (payment, email_send, social_post, etc.)
            details: Dictionary of action-specific details
            description: Human-readable description
            priority: high, medium, or low
            expires_in_hours: Hours until expiry (None = no expiry)

        Returns:
            Path to created approval file
        """
        # Generate filename
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        safe_desc = description[:30].replace(' ', '_').replace('/', '_')
        filename = f"APPROVAL_REQUIRED_{action_type}_{safe_desc}_{timestamp}.md"
        filepath = self.pending_approval / filename
        
        # Calculate expiry
        expires = None
        if expires_in_hours:
            expires = (datetime.now() + timedelta(hours=expires_in_hours)).isoformat()
        
        # Format details as YAML
        details_yaml = '\n'.join(f'{k}: {json.dumps(v) if isinstance(v, (dict, list)) else v}' 
                                  for k, v in details.items())
        
        # Format details for display
        details_display = self._format_details_display(action_type, details)
        
        content = f'''---
type: approval_request
action: {action_type}
created: {datetime.now().isoformat()}
status: pending
priority: {priority}
{f'expires: {expires}' if expires else ''}
{details_yaml}
---

# Approval Required: {description}

## Action Details

{details_display}

## Description

{description if description else 'No description provided.'}

## Instructions

### To Approve
1. Review the details above carefully
2. Move this file to `Approved/` folder
3. AI will execute the action automatically

### To Reject
1. Move this file to `Rejected/` folder
2. Add reason for rejection in notes below

## Notes

*Add comments or rejection reason here...*

---
*Generated by HITL Approval Workflow v0.1*
'''
        
        filepath.write_text(content, encoding='utf-8')
        
        # Log creation
        self._log_event('approval_created', str(filepath), details)
        
        print(f"[OK] Created approval request: {filepath}")
        return filepath

    def _format_details_display(self, action_type: str, details: Dict) -> str:
        """Format details for display in approval file."""
        if action_type == 'payment':
            return f"""- **Amount:** ${details.get('amount', 'N/A')}
- **Recipient:** {details.get('recipient', 'N/A')}
- **Reason:** {details.get('reason', 'N/A')}
- **Due Date:** {details.get('due_date', 'N/A')}"""
        
        elif action_type == 'email_send':
            return f"""- **To:** {details.get('to', 'N/A')}
- **Subject:** {details.get('subject', 'N/A')}
- **Body Preview:** {details.get('body', '')[:200]}..."""
        
        elif action_type == 'social_post':
            return f"""- **Platform:** {details.get('platform', 'N/A')}
- **Content:** {details.get('content', 'N/A')[:200]}...
- **Hashtags:** {details.get('hashtags', 'N/A')}"""
        
        elif action_type == 'whatsapp_send':
            return f"""- **To:** {details.get('to', 'N/A')}
- **Message:** {details.get('message', 'N/A')[:200]}..."""
        
        else:
            return '\n'.join(f'- **{k.replace("_", " ").title()}:** {v}' for k, v in details.items())

    def get_pending_approvals(self) -> List[Path]:
        """Get all pending approval files."""
        return list(self.pending_approval.glob('APPROVAL_REQUIRED_*.md'))

    def get_approved_actions(self) -> List[Path]:
        """Get all approved action files ready for execution."""
        return list(self.approved.glob('APPROVAL_REQUIRED_*.md'))

    def get_rejected_actions(self) -> List[Path]:
        """Get all rejected action files."""
        return list(self.rejected.glob('APPROVAL_REQUIRED_*.md'))

    def execute_approval(self, filepath: Path) -> bool:
        """
        Execute an approved action.

        Args:
            filepath: Path to approval file

        Returns:
            True if execution successful
        """
        content = filepath.read_text(encoding='utf-8')
        
        # Parse frontmatter
        action_type = self._parse_field(content, 'action:')
        
        if not action_type:
            print(f"Error: Could not determine action type from {filepath}")
            return False
        
        print(f"Executing {action_type} action from {filepath.name}")
        
        # Execute based on type
        success = False
        if action_type == 'payment':
            success = self._execute_payment(filepath, content)
        elif action_type == 'email_send':
            success = self._execute_email(filepath, content)
        elif action_type == 'social_post':
            success = self._execute_social_post(filepath, content)
        elif action_type == 'whatsapp_send':
            success = self._execute_whatsapp(filepath, content)
        else:
            print(f"Unknown action type: {action_type}")
            return False
        
        if success:
            # Move to Done
            done_path = self.done / filepath.name
            filepath.rename(done_path)
            print(f"[OK] Action completed. File moved to Done folder.")
            
            # Log execution
            self._log_event('approval_executed', str(done_path), {'action_type': action_type})
        else:
            print(f"[FAIL] Action failed. File remains in Approved folder.")
        
        return success

    def _parse_field(self, content: str, field: str) -> Optional[str]:
        """Parse a field from frontmatter."""
        for line in content.split('\n'):
            if line.startswith(field):
                return line.split(':', 1)[1].strip()
        return None

    def _execute_payment(self, filepath: Path, content: str) -> bool:
        """Execute payment action."""
        # Parse details
        amount = self._parse_field(content, 'amount:')
        recipient = self._parse_field(content, 'recipient:')
        
        print(f"  Payment: ${amount} to {recipient}")
        
        # In real implementation, this would call payment MCP
        # For now, just log the action
        print("  [Would execute payment via MCP server]")
        
        return True

    def _execute_email(self, filepath: Path, content: str) -> bool:
        """Execute email send action."""
        to = self._parse_field(content, 'to:')
        subject = self._parse_field(content, 'subject:')
        
        print(f"  Email to: {to}")
        print(f"  Subject: {subject}")
        
        # In real implementation, this would call email MCP
        print("  [Would send email via MCP server]")
        
        return True

    def _execute_social_post(self, filepath: Path, content: str) -> bool:
        """Execute social media post action."""
        platform = self._parse_field(content, 'platform:')
        content_preview = self._parse_field(content, 'content:')
        
        print(f"  Platform: {platform}")
        print(f"  Content: {content_preview[:50]}...")
        
        # In real implementation, this would call social media MCP
        print("  [Would post via MCP server]")
        
        return True

    def _execute_whatsapp(self, filepath: Path, content: str) -> bool:
        """Execute WhatsApp message action."""
        to = self._parse_field(content, 'to:')
        
        print(f"  WhatsApp to: {to}")
        
        # In real implementation, this would call WhatsApp MCP
        print("  [Would send message via WhatsApp MCP]")
        
        return True

    def check_expiry(self):
        """Check for expired approvals and move to Rejected."""
        now = datetime.now()
        
        for filepath in self.pending_approval.glob('APPROVAL_REQUIRED_*.md'):
            content = filepath.read_text(encoding='utf-8')
            expires = self._parse_field(content, 'expires:')
            
            if expires:
                try:
                    expiry_time = datetime.fromisoformat(expires)
                    if now > expiry_time:
                        # Move to Rejected
                        rejected_path = self.rejected / filepath.name
                        filepath.rename(rejected_path)
                        
                        # Add expiry note
                        note = f"\n\n**EXPIRED:** This approval expired at {expires}\n"
                        content += note
                        rejected_path.write_text(content, encoding='utf-8')
                        
                        # Log
                        self._log_event('approval_expired', str(rejected_path), {})
                        
                except ValueError:
                    pass

    def _log_event(self, event_type: str, filepath: str, details: Dict):
        """Log an event to Logs folder."""
        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'event_type': event_type,
            'filepath': filepath,
            'details': details
        }
        
        # Append to daily log
        log_file = self.logs / f"approvals_{datetime.now().strftime('%Y-%m-%d')}.json"
        
        logs = []
        if log_file.exists():
            try:
                logs = json.loads(log_file.read_text(encoding='utf-8'))
            except:
                logs = []
        
        logs.append(log_entry)
        log_file.write_text(json.dumps(logs, indent=2), encoding='utf-8')

    def watch(self, check_interval: int = 30):
        """
        Watch Approved folder for actions to execute.

        Args:
            check_interval: Seconds between checks
        """
        import time
        
        print(f"=== HITL Approval Watcher ===")
        print(f"Monitoring: {self.approved}")
        print(f"Press Ctrl+C to stop\n")
        
        try:
            while True:
                # Check for approved actions
                approved = self.get_approved_actions()
                
                for filepath in approved:
                    self.execute_approval(filepath)
                
                # Check expiry
                self.check_expiry()
                
                time.sleep(check_interval)
                
        except KeyboardInterrupt:
            print("\nWatcher stopped by user.")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description='HITL Approval Workflow')
    parser.add_argument('vault_path', nargs='?', help='Path to Obsidian vault')
    parser.add_argument('--create-approval', action='store_true', help='Create new approval')
    parser.add_argument('--type', type=str, help='Action type (payment, email_send, etc.)')
    parser.add_argument('--amount', type=float, help='Payment amount')
    parser.add_argument('--recipient', type=str, help='Payment recipient')
    parser.add_argument('--to', type=str, help='Email/WhatsApp recipient')
    parser.add_argument('--subject', type=str, help='Email subject')
    parser.add_argument('--content', type=str, help='Message/post content')
    parser.add_argument('--priority', type=str, default='medium', help='Priority (high/medium/low)')
    parser.add_argument('--expires', type=int, help='Expiry in hours')
    parser.add_argument('--check-approved', action='store_true', help='Check and execute approved actions')
    parser.add_argument('--watch', action='store_true', help='Run in watch mode')
    parser.add_argument('--interval', type=int, default=30, help='Watch check interval (seconds)')
    
    args = parser.parse_args()
    
    # Get vault path
    if args.vault_path:
        vault_path = Path(args.vault_path).resolve()
    else:
        vault_path = Path(__file__).parent.parent / 'AI_Employee_Vault'
        vault_path = vault_path.resolve()
    
    if not vault_path.exists():
        print(f"Error: Vault path does not exist: {vault_path}")
        sys.exit(1)
    
    approval = HITLApproval(str(vault_path))
    
    if args.create_approval:
        if not args.type:
            print("Error: --type is required")
            sys.exit(1)
        
        details = {}
        description = ""
        
        if args.type == 'payment':
            if not args.amount or not args.recipient:
                print("Error: --amount and --recipient required for payment")
                sys.exit(1)
            details = {
                'amount': args.amount,
                'recipient': args.recipient,
                'reason': 'Manual approval request'
            }
            description = f"Payment of ${args.amount} to {args.recipient}"
        
        elif args.type == 'email_send':
            if not args.to or not args.subject:
                print("Error: --to and --subject required for email")
                sys.exit(1)
            details = {
                'to': args.to,
                'subject': args.subject,
                'body': args.content or ''
            }
            description = f"Send email to {args.to}"
        
        elif args.type == 'social_post':
            details = {
                'platform': 'linkedin',
                'content': args.content or '',
                'hashtags': ''
            }
            description = "Post to social media"
        
        approval.create_approval(
            action_type=args.type,
            details=details,
            description=description,
            priority=args.priority,
            expires_in_hours=args.expires
        )
    
    elif args.check_approved:
        print("Checking for approved actions...")
        approved = approval.get_approved_actions()
        
        if approved:
            for filepath in approved:
                approval.execute_approval(filepath)
        else:
            print("No approved actions found.")
    
    elif args.watch:
        approval.watch(check_interval=args.interval)
    
    else:
        parser.print_help()


if __name__ == '__main__':
    main()
