"""
Plan Generator - Creates Plan.md files for complex multi-step tasks.

When Claude Code detects complex tasks requiring multiple steps,
this utility creates structured plans with checkboxes, dependencies,
and progress tracking.

Usage:
    python plan_generator.py /path/to/vault --create-plan "Task description"
    python plan_generator.py /path/to/vault --analyze-needs-action
"""

import os
import sys
import argparse
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Optional


class PlanGenerator:
    """
    Generates Plan.md files for complex tasks.
    """

    def __init__(self, vault_path: str):
        """
        Initialize the plan generator.

        Args:
            vault_path: Path to the Obsidian vault root
        """
        self.vault_path = Path(vault_path)
        self.plans_folder = self.vault_path / 'Plans'
        self.needs_action = self.vault_path / 'Needs_Action'
        
        # Ensure folders exist
        self.plans_folder.mkdir(parents=True, exist_ok=True)
        self.needs_action.mkdir(parents=True, exist_ok=True)

    def create_plan(self, title: str, description: str, 
                    related_items: Optional[List[str]] = None,
                    priority: str = 'medium',
                    estimated_duration: str = '1 hour',
                    custom_steps: Optional[List[str]] = None) -> Path:
        """
        Create a new plan.

        Args:
            title: Plan title
            description: Plan description/objective
            related_items: List of related action files
            priority: high, medium, or low
            estimated_duration: Estimated time to complete
            custom_steps: Custom steps instead of auto-generated

        Returns:
            Path to created plan file
        """
        # Generate filename
        timestamp = datetime.now().strftime('%Y-%m-%d_%H%M%S')
        task_type = self._infer_task_type(title, description)
        filename = f"Plan_{task_type}_{timestamp}.md"
        filepath = self.plans_folder / filename
        
        # Generate steps if not provided
        if not custom_steps:
            steps = self._generate_steps(title, description, related_items)
        else:
            steps = custom_steps
        
        # Format related items
        related_md = ''
        if related_items:
            related_md = '\n'.join(f'  - {item}' for item in related_items)
        
        content = f'''---
type: plan
created: {datetime.now().isoformat()}
status: in_progress
priority: {priority}
estimated_duration: {estimated_duration}
related_items:
{related_md}
---

# Task Plan: {title}

## Objective
{description}

## Steps

{self._format_steps(steps)}

## Dependencies
*List any dependencies or blockers here*

## Notes

### Research Findings
*Add findings here*

### Blockers
*List any blockers here*

## Completion Criteria
- [ ] All steps completed
- [ ] Related files moved to Done folder
- [ ] Dashboard updated with outcome

---
*Generated by Plan Generator v0.1*
'''
        
        filepath.write_text(content, encoding='utf-8')
        print(f"[OK] Created plan: {filepath}")
        return filepath

    def _infer_task_type(self, title: str, description: str) -> str:
        """Infer task type from title and description."""
        text = f"{title} {description}".lower()
        
        if any(kw in text for kw in ['email', 'reply', 'respond']):
            return 'EmailResponse'
        elif any(kw in text for kw in ['invoice', 'payment', 'bill']):
            return 'PaymentProcessing'
        elif any(kw in text for kw in ['project', 'launch', 'init']):
            return 'ProjectLaunch'
        elif any(kw in text for kw in ['urgent', 'emergency', 'crisis']):
            return 'CrisisManagement'
        elif any(kw in text for kw in ['whatsapp', 'message', 'chat']):
            return 'MessageResponse'
        elif any(kw in text for kw in ['file', 'document', 'review']):
            return 'DocumentReview'
        else:
            return 'GeneralTask'

    def _generate_steps(self, title: str, description: str, 
                        related_items: Optional[List[str]] = None) -> List[Dict]:
        """
        Generate steps based on task type.

        Returns:
            List of step dictionaries with phase and actions
        """
        task_type = self._infer_task_type(title, description)
        
        # Default steps for common task types
        if task_type == 'EmailResponse':
            return [
                {'phase': 'Phase 1: Information Gathering', 'actions': [
                    'Read email content carefully',
                    'Identify key questions or requests',
                    'Check sender history and context',
                    'Review company handbook for response guidelines'
                ]},
                {'phase': 'Phase 2: Draft Response', 'actions': [
                    'Draft initial response',
                    'Review for tone and clarity',
                    'Add any necessary attachments or links',
                    'Save to Pending_Approval if sensitive'
                ]},
                {'phase': 'Phase 3: Send and Follow-up', 'actions': [
                    'Get approval if required',
                    'Send response via email MCP',
                    'Schedule follow-up reminder if needed',
                    'Move email to Done folder'
                ]}
            ]
        elif task_type == 'PaymentProcessing':
            return [
                {'phase': 'Phase 1: Verification', 'actions': [
                    'Locate original invoice',
                    'Verify invoice details (amount, due date, vendor)',
                    'Check payment history for duplicates',
                    'Verify against company budget'
                ]},
                {'phase': 'Phase 2: Approval', 'actions': [
                    'Create payment approval request',
                    'Move to Pending_Approval folder',
                    'Wait for human approval',
                    'Document approval reference'
                ]},
                {'phase': 'Phase 3: Processing', 'actions': [
                    'Process payment via accounting system',
                    'Record transaction in Accounting/',
                    'Send payment confirmation',
                    'File invoice in Invoices/'
                ]}
            ]
        elif task_type == 'MessageResponse':
            return [
                {'phase': 'Phase 1: Understand Message', 'actions': [
                    'Read message content',
                    'Identify urgency level',
                    'Check conversation history',
                    'Determine required action'
                ]},
                {'phase': 'Phase 2: Prepare Response', 'actions': [
                    'Draft response message',
                    'Review for appropriateness',
                    'Save to Pending_Approval if needed'
                ]},
                {'phase': 'Phase 3: Respond', 'actions': [
                    'Get approval if required',
                    'Send response',
                    'Document in Logs/',
                    'Move to Done folder'
                ]}
            ]
        else:
            # Generic steps
            return [
                {'phase': 'Phase 1: Analysis', 'actions': [
                    'Review task requirements',
                    'Gather necessary information',
                    'Identify constraints and dependencies'
                ]},
                {'phase': 'Phase 2: Execution', 'actions': [
                    'Complete primary task actions',
                    'Document progress',
                    'Handle any issues or blockers'
                ]},
                {'phase': 'Phase 3: Completion', 'actions': [
                    'Verify task completion',
                    'Update relevant files',
                    'Move to Done folder',
                    'Update Dashboard'
                ]}
            ]

    def _format_steps(self, steps: List[Dict]) -> str:
        """Format steps as markdown."""
        output = []
        for step in steps:
            phase = step.get('phase', '')
            actions = step.get('actions', [])
            
            if phase:
                output.append(f"### {phase}")
            
            for action in actions:
                output.append(f"- [ ] {action}")
            
            output.append("")  # Empty line between phases
        
        return '\n'.join(output)

    def analyze_needs_action(self) -> List[Path]:
        """
        Analyze Needs_Action folder and suggest plans for complex items.

        Returns:
            List of created plan files
        """
        created_plans = []
        
        # Get all action files
        action_files = list(self.needs_action.glob('*.md'))
        
        for filepath in action_files:
            content = filepath.read_text(encoding='utf-8')
            
            # Check if already has a plan reference
            if 'Plan_' in content:
                continue
            
            # Analyze complexity
            complexity = self._assess_complexity(content)
            
            if complexity['score'] >= 3:
                # Create plan for complex items
                plan = self.create_plan(
                    title=filepath.stem.replace('_', ' '),
                    description=complexity['summary'],
                    related_items=[str(filepath.relative_to(self.vault_path))],
                    priority=complexity['priority'],
                    custom_steps=complexity.get('suggested_steps')
                )
                created_plans.append(plan)
                
                # Update action file to reference plan
                self._link_action_to_plan(filepath, plan)
        
        return created_plans

    def _assess_complexity(self, content: str) -> Dict:
        """
        Assess task complexity from action file content.

        Returns:
            Dictionary with score, priority, summary, and suggested_steps
        """
        score = 0
        priority = 'medium'
        summary = "Process this task according to company guidelines."
        suggested_steps = None
        
        # Check for priority indicators
        if 'priority: high' in content:
            score += 2
            priority = 'high'
        if any(kw in content.lower() for kw in ['urgent', 'asap', 'emergency']):
            score += 2
            priority = 'high'
        
        # Check for multiple action items
        if content.count('- [ ]') >= 3:
            score += 1
        
        # Check for attachments or files
        if 'FILE_' in content:
            score += 1
            summary = "Review and process the attached file."
        
        # Check for email content
        if 'type: email' in content:
            score += 1
            if 'invoice' in content.lower() or 'payment' in content.lower():
                summary = "Process email regarding payment or invoice."
                suggested_steps = None  # Will use default PaymentProcessing steps
            else:
                summary = "Draft appropriate response to email."
        
        # Check for WhatsApp messages
        if 'type: whatsapp' in content:
            score += 1
            summary = "Respond to urgent WhatsApp message."
        
        return {
            'score': score,
            'priority': priority,
            'summary': summary,
            'suggested_steps': suggested_steps
        }

    def _link_action_to_plan(self, action_file: Path, plan_file: Path):
        """Add plan reference to action file."""
        content = action_file.read_text(encoding='utf-8')
        
        # Add plan reference to frontmatter or end
        plan_ref = f"\n\n**Related Plan:** [[{plan_file.stem}]]\n"
        
        if '---' in content:
            # Insert before the last --- (end of frontmatter)
            parts = content.rsplit('---', 1)
            if len(parts) == 2:
                content = parts[0] + f'\nplan: {plan_file.name}' + '---' + parts[1]
        
        content += plan_ref
        action_file.write_text(content, encoding='utf-8')

    def get_active_plans(self) -> List[Path]:
        """Get all active (in_progress) plans."""
        active = []
        for plan_file in self.plans_folder.glob('Plan_*.md'):
            content = plan_file.read_text(encoding='utf-8')
            if 'status: in_progress' in content or 'status: pending' in content:
                active.append(plan_file)
        return active

    def update_plan_status(self, plan_file: Path, new_status: str) -> bool:
        """
        Update plan status.

        Args:
            plan_file: Path to plan file
            new_status: New status (pending, in_progress, blocked, completed, rejected)

        Returns:
            True if successful
        """
        content = plan_file.read_text(encoding='utf-8')
        
        # Replace status line
        import re
        content = re.sub(r'status: \w+', f'status: {new_status}', content)
        
        plan_file.write_text(content, encoding='utf-8')
        return True


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description='Plan Generator for AI Employee')
    parser.add_argument('vault_path', nargs='?', help='Path to Obsidian vault')
    parser.add_argument('--create-plan', type=str, help='Create plan with title')
    parser.add_argument('--description', type=str, help='Plan description')
    parser.add_argument('--priority', type=str, default='medium', help='Priority (high/medium/low)')
    parser.add_argument('--analyze-needs-action', action='store_true', help='Analyze and create plans')
    parser.add_argument('--related', type=str, nargs='+', help='Related action files')
    
    args = parser.parse_args()
    
    # Get vault path
    if args.vault_path:
        vault_path = Path(args.vault_path).resolve()
    else:
        vault_path = Path(__file__).parent.parent / 'AI_Employee_Vault'
        vault_path = vault_path.resolve()
    
    if not vault_path.exists():
        print(f"Error: Vault path does not exist: {vault_path}")
        sys.exit(1)
    
    generator = PlanGenerator(str(vault_path))
    
    if args.create_plan:
        generator.create_plan(
            title=args.create_plan,
            description=args.description or "Complete this task according to guidelines.",
            priority=args.priority,
            related_items=args.related
        )
    
    elif args.analyze_needs_action:
        print(f"=== Analyzing Needs_Action Folder ===")
        plans = generator.analyze_needs_action()
        if plans:
            print(f"\n[OK] Created {len(plans)} plan(s):")
            for plan in plans:
                print(f"  - {plan.name}")
        else:
            print("\nNo complex tasks requiring plans found.")
    
    else:
        parser.print_help()


if __name__ == '__main__':
    main()
